apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgre
          image: postgres:15.0
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: "kubenews"
          - name: POSTGRES_USER
            value: "kubenews"
          - name: POSTGRES_PASSWORD
            value: "Pg#123"
---

apiVersion: v1 
kind: Service 
metadata:
  name: postgre
spec:  
  selector: 
    app: postgre
  ports: 
    - port: 5432
  type: ClusterIP

---
